@baseUrl = http://localhost:3000/crm

### Get Inquiry List
GET {{baseUrl}}/inquiry

### Get Inquiry by ID
GET {{baseUrl}}/inquiry/accb1539-39ed-4cae-8f55-3a73ff719db3

### Create Inquiry
POST {{baseUrl}}/inquiry
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "message": "I am interested in your services"
}

### Update Inquiry
PUT {{baseUrl}}/inquiry/01bbd8e5-bec4-4e76-a99c-4f8a002f188f
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}
