@baseUrl = http://localhost:3000/crm/inquiry
### Get all inquiries
GET {{baseUrl}}

### Get inquiry by id
GET {{baseUrl}}/

### Create inquiry
POST {{baseUrl}}

Content-Type: application/json

{
  "email": "assanali.tungat@aneko.io",
  "message": "test"
}

### Update inquiry
PATCH {{baseUrl}}/e3e7d85c-3b8d-43f2-9579-ebcf55902bad
Content-Type: application/json

{
    "message": "not test!!!"
}

### Delete inquiry
DELETE {{baseUrl}}/184ecbe1-b11d-4900-8beb-10fefe5b7bef
